fix set executable + order to reversly when stack specified uninstall or sto²

diff --git a/docker-stacks/simva b/docker-stacks/simva
--- a/docker-stacks/simva
+++ b/docker-stacks/simva
@@ -183,7 +183,7 @@ function execute_before_hooks() {
     shift
     local folder="${SIMVA_HOME}/etc/hooks"
     local stacks="${SIMVA_STACKS}"
-    if [[ $# -gt 0 ]]; then
+        if [[ $# -gt 0 ]]; then
         stacks=$@
     fi
 
@@ -355,7 +355,10 @@ function run_scripts_from_folder() {
 function setExecutable_scripts_from_folder() {
     local folder=${1}
     if [[ -d "${folder}" ]]; then
-        chmod a+x ${folder}/*
+        for FILE in $(find ${folder} -iname \*.sh -type f | sort); do
+            echo "Set executable script file : ${FILE}"
+            chmod a+x ${FILE}
+        done
     fi
 }
 
@@ -417,6 +420,72 @@ function install() {
     execute_after_hooks ${phase} ${stacks}
 }
 
+# remove containers
+function uninstall() {
+    if [[ $# -lt 1 ]]; then
+        echo >&2 "missing wait_time";
+        exit 1;
+    fi
+    local wait_time=${1}
+    shift
+
+    local phase="uninstall"
+    local stacks=${SIMVA_STACKS}
+    if [[ $# -gt 0 ]]; then
+        stacks=$@
+    fi
+    local reverse_stacks=$(for s in ${stacks[@]}; do echo $s; done | sort -r)
+    execute_before_hooks ${phase} ${reverse_stacks}
+    docker_compose_stacks "${reverse_stacks}" ${wait_time} "down -v"
+    execute_after_hooks ${phase} ${reverse_stacks}
+}
+
+
+# start stacks
+function start() {
+    if [[ $# -lt 1 ]]; then
+        echo >&2 "missing wait_time";
+        exit 1;
+    fi
+    local wait_time=${1}
+    shift
+
+    local stacks=${SIMVA_STACKS}
+    if [[ $# -gt 0 ]]; then
+        stacks=$@
+    fi
+    if [[ ! -e "${SIMVA_PROJECT_DIR}/.simva-initialized" ]]; then
+        wait_time=20;
+        recho "SIMVA it is not initialized, this launch will take longer than normal."
+    fi
+    local phase="start"
+    execute_before_hooks ${phase} ${stacks}
+    docker_compose_stacks "${stacks}" ${wait_time} "up -d"
+    execute_after_hooks ${phase} ${stacks}
+    touch "${SIMVA_PROJECT_DIR}/.simva-initialized"
+}
+
+# stop stacks
+function stop() {
+    if [[ $# -lt 1 ]]; then
+        echo >&2 "missing wait_time";
+        exit 1;
+    fi
+    local wait_time=${1}
+    shift
+
+    local phase="stop"
+    local stacks=${SIMVA_STACKS}
+    if [[ $# -gt 0 ]]; then
+        stacks=$@
+    fi
+    local reverse_stacks=$(for s in ${stacks[@]}; do echo $s; done | sort -r)
+    execute_before_hooks ${phase} ${reverse_stacks}
+    docker_compose_stacks "${reverse_stacks}" ${wait_time} ${phase}
+    execute_after_hooks ${phase} ${reverse_stacks}
+}
+
+
 # Set executable 
 function setExecutable() {
     if [[ $# -lt 1 ]]; then
@@ -440,6 +509,14 @@ function setExecutable() {
         setExecutable_scripts_from_folder ${folder}
         folder="${HooksFolder}/after-stop.d"
         setExecutable_scripts_from_folder ${folder}
+        folder="${HooksFolder}/before-install.d"
+        setExecutable_scripts_from_folder ${folder}
+        folder="${HooksFolder}/before-uninstall.d"
+        setExecutable_scripts_from_folder ${folder}
+        folder="${HooksFolder}/before-start.d"
+        setExecutable_scripts_from_folder ${folder}
+        folder="${HooksFolder}/before-stop.d"
+        setExecutable_scripts_from_folder ${folder}
     done;
     HooksFolder="${SIMVA_HOME}/etc/hooks"
     folder="${HooksFolder}/after-install.d"
@@ -450,69 +527,14 @@ function setExecutable() {
     setExecutable_scripts_from_folder ${folder}
     folder="${HooksFolder}/after-stop.d"
     setExecutable_scripts_from_folder ${folder}
-}
-
-# remove containers
-function uninstall() {
-    if [[ $# -lt 1 ]]; then
-        echo >&2 "missing wait_time";
-        exit 1;
-    fi
-    local wait_time=${1}
-    shift
-
-    local phase="uninstall"
-    local reverse_stacks=$(for s in ${SIMVA_STACKS}; do echo $s; done | sort -r)
-    if [[ $# -gt 0 ]]; then
-        reverse_stacks=$@
-    fi
-    execute_before_hooks ${phase} ${reverse_stacks}
-    docker_compose_stacks "${reverse_stacks}" ${wait_time} "down -v"
-    execute_after_hooks ${phase} ${reverse_stacks}
-}
-
-
-# start stacks
-function start() {
-    if [[ $# -lt 1 ]]; then
-        echo >&2 "missing wait_time";
-        exit 1;
-    fi
-    local wait_time=${1}
-    shift
-
-    local stacks=${SIMVA_STACKS}
-    if [[ $# -gt 0 ]]; then
-        stacks=$@
-    fi
-    if [[ ! -e "${SIMVA_PROJECT_DIR}/.simva-initialized" ]]; then
-        wait_time=20;
-        recho "SIMVA it is not initialized, this launch will take longer than normal."
-            fi
-    local phase="start"
-    execute_before_hooks ${phase} ${stacks}
-    docker_compose_stacks "${stacks}" ${wait_time} "up -d"
-    execute_after_hooks ${phase} ${stacks}
-    touch "${SIMVA_PROJECT_DIR}/.simva-initialized"
-}
-
-# stop stacks
-function stop() {
-    if [[ $# -lt 1 ]]; then
-        echo >&2 "missing wait_time";
-        exit 1;
-    fi
-    local wait_time=${1}
-    shift
-
-    local phase="stop"
-    local stacks=$(for s in ${SIMVA_STACKS}; do echo $s; done | sort -r)
-    if [[ $# -gt 0 ]]; then
-        stacks=$@
-    fi
-    execute_before_hooks ${phase} ${stacks}
-    docker_compose_stacks "${stacks}" ${wait_time} ${phase}
-    execute_after_hooks ${phase} ${stacks}
+    folder="${HooksFolder}/before-install.d"
+    setExecutable_scripts_from_folder ${folder}
+    folder="${HooksFolder}/before-uninstall.d"
+    setExecutable_scripts_from_folder ${folder}
+    folder="${HooksFolder}/before-start.d"
+    setExecutable_scripts_from_folder ${folder}
+    folder="${HooksFolder}/before-stop.d"
+    setExecutable_scripts_from_folder ${folder}
 }
 
 # log stack
