comment entrypoint

diff --git a/docker-stacks/06-simva/docker-compose.yml b/docker-stacks/06-simva/docker-compose.yml
--- a/docker-stacks/06-simva/docker-compose.yml
+++ b/docker-stacks/06-simva/docker-compose.yml
@@ -37,36 +37,36 @@ services:
   simva-api:
     << : *default-opts
     image: node:14
-    entrypoint: >
-      /bin/sh -c '
-      /container-tools/wait-for -t $${WAIT_TIMEOUT} -it $${SSO_HOST};
-        if [ ! -e "/etc/ssl/certs/internal-CA.pem" ]; then
-          cp /var/lib/simva/ca/rootCA.pem "/etc/ssl/certs/internal-CA.pem";
-          cat "/etc/ssl/certs/internal-CA.pem" >> /etc/ssl/cert.pem;
-        fi;
-        wait_time=$${MC_WAIT_TIME};
-        count=$${MC_MAX_RETRIES};
-        done="ko";
-        while [ $$count -gt 0 ] && [ "$$done" != "ok" ]; do
-          echo 1>&2 "Checking Keycloak availability for Simva API: $$(($${MC_MAX_RETRIES}-$$count+1)) pass";
-          wget "$${SSO_PROTOCOL}://$${SSO_HOST}/auth/realms/$${SSO_REALM}/.well-known/openid-configuration" -O - >/dev/null;
-          ret=$$?;
-          if [ $$ret -eq 0 ]; then
-            done="ok";
-          else
-            echo 1>&2 "Keycloak not available, waiting $${wait_time}s";
-            sleep $${wait_time};
-          fi;
-          count=$$((count-1));
-        done;
-        if [ $$count -eq 0 ] && [ "$$done" != "ok" ]; then
-          echo 1>&2 "Keycloak not available !";
-          exit 1
-        fi;
-        if [ "$$done" == "ok" ]; then
-          echo 1>&2 "Keycloak available !";
-        fi;
-      '
+#    entrypoint: >
+#      /bin/sh -c '
+#      /container-tools/wait-for -t $${WAIT_TIMEOUT} -it $${SSO_HOST};
+#        if [ ! -e "/etc/ssl/certs/internal-CA.pem" ]; then
+#          cp /var/lib/simva/ca/rootCA.pem "/etc/ssl/certs/internal-CA.pem";
+#          cat "/etc/ssl/certs/internal-CA.pem" >> /etc/ssl/cert.pem;
+#        fi;
+#        wait_time=$${MC_WAIT_TIME};
+#        count=$${MC_MAX_RETRIES};
+#        done="ko";
+#        while [ $$count -gt 0 ] && [ "$$done" != "ok" ]; do
+#          echo 1>&2 "Checking Keycloak availability for Simva API: $$(($${MC_MAX_RETRIES}-$$count+1)) pass";
+#          wget "$${SSO_PROTOCOL}://$${SSO_HOST}/auth/realms/$${SSO_REALM}/.well-known/openid-configuration" -O - >/dev/null;
+#          ret=$$?;
+#          if [ $$ret -eq 0 ]; then
+#            done="ok";
+#          else
+#            echo 1>&2 "Keycloak not available, waiting $${wait_time}s";
+#            sleep $${wait_time};
+#          fi;
+#          count=$$((count-1));
+#        done;
+#        if [ $$count -eq 0 ] && [ "$$done" != "ok" ]; then
+#          echo 1>&2 "Keycloak not available !";
+#          exit 1
+#        fi;
+#        if [ "$$done" == "ok" ]; then
+#          echo 1>&2 "Keycloak available !";
+#        fi;
+#      '
     command: bash -c "mkdir -p /storage && cd /app && chmod +x docker-startup.sh && ./docker-startup.sh"
     stdin_open: true
     tty: true
